version: "3"

services:
  eln:
    build:
      dockerfile: Dockerfile-standalone
    ports:
      - "8081:8080"
    volumes:
      - ./data/pages:/srv/www/data/pages
      - ./data/media:/srv/www/data/media
