<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: till
 * Date: Thu, 23 Jun 2022 21:49:13 +0200
 */

$conf['title'] = 'ELN@LabInform';
$conf['start'] = 'index';
$conf['tagline'] = 'Electronic Laboratory Notebook component';
$conf['dmode'] = 0750;
$conf['fmode'] = 0640;
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['toptoclevel'] = '2';
$conf['useheading'] = 'content';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['defer_js'] = 0;
$conf['dnslookups'] = 0;
$conf['plugin']['data']['edit_content_only'] = 1;
$conf['plugin']['include']['showfooter'] = 0;
$conf['plugin']['include']['showdate'] = 0;
$conf['plugin']['include']['showuser'] = 0;
$conf['plugin']['include']['showcomments'] = 0;
$conf['plugin']['include']['showlinkbacks'] = 0;
$conf['plugin']['include']['showtags'] = 0;
$conf['plugin']['include']['showeditbtn'] = 0;
